on: push

jobs:
    replicate-file:
        runs-on: ubuntu-latest
        name: Replicate File

        steps:
        - name: Checkout Project A
          uses: actions/checkout@v2
          with:
            path: ./repo1

        - name: Checkout Project B
          uses: actions/checkout@master
          with: 
            repository: muthugit/repo2
            token: ${{ secrets.GITHUB_TOKEN }}
            path: ./repo2

        - name: Copy/Create file
          run: |
            echo "this is new file" > new.md

        - name: Push Project B
          run: |
            cd ./repo2
            git add .
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -am "File Replicated from Project A"
            git push
